### ISSUE TITLE
Error while trying to build from source on WSL2

### ISSUE THREAD

**Issue by crazyuploader** [RIPE-NCC/ripe-atlas-software-probe#47]
`OS: Windows 10 Pro (Ubuntu on WSL2)`

While trying to build from source, it threw me this as an error, attaching screenshot below. Please let me know if it's even possible to build on WSL2 altogether, or I am missing something out.

![image](https://user-images.githubusercontent.com/49350241/90739321-3f470680-e2ec-11ea-857a-06b1afe30553.png)

**Comment by PhilipHomburg** [comment]
please try the devel branch

**Comment by crazyuploader** [comment]
> please try the devel branch

Sorry to mention that, but it didn't work either ;)

**Comment by PhilipHomburg** [comment]
Ah, correct. The devel branch needs to be updated. It seems that I never updated the probe-busybox submodule.

**Comment by PhilipHomburg** [comment]
I just pushed an undate to the devel branch. Could you please try again

**Comment by crazyuploader** [comment]
> I just pushed an undate to the devel branch. Could you please try again

Alright lemme try

**Comment by crazyuploader** [comment]
Sadly, it still fails.... One more thing, is `python` a requirement? 

![image](https://user-images.githubusercontent.com/49350241/91451937-9bd19500-e89b-11ea-8445-6b03db4c33ff.png)

**Comment by crazyuploader** [comment]
Tried installing `bionic 18.04` but turns out since the system isn't booted with `systemd`, we can't install it

```
System has not been booted with systemd as init system (PID 1). Can't operate.
```

**Comment by PhilipHomburg** [comment]
I don't understand the error you get. The current version in the devel branch refers to 2.3.0 of the probe-busybox, where date no longer calls stime.

Currently the software probe only works with systemd. However, patches to make it work for sysv are welcome.

**Comment by PhilipHomburg** [comment]
Master now refers to a version of busybox without calls to stime.
